USE master;
GO

DROP DATABASE ProyectoWeb_Catalogo_Pedidos;
GO

CREATE DATABASE ProyectoWeb_Catalogo_Pedidos;
GO

USE ProyectoWeb_Catalogo_Pedidos;
GO

CREATE TABLE ADMINISTRADOR
(
	Id INT NOT NULL IDENTITY(1,1),
	Usuario NVARCHAR(20) NOT NULL,
	Contrasenia NVARCHAR(MAX) NOT NULL,
	
	CONSTRAINT PK_ADMINISTRADOR PRIMARY KEY(Id),
	CONSTRAINT UK_Usuario_ADMINISTRADOR UNIQUE(Usuario)
);
GO

CREATE TABLE CLIENTE
(
	Id INT NOT NULL IDENTITY(1,1),
	Usuario NVARCHAR(20) NOT NULL,
	Contrasenia NVARCHAR(MAX) NOT NULL,
	NombreFantasia NVARCHAR(100),
	Rut INT,
	RazonSocial NVARCHAR(100),
	Descuento NUMERIC(5,2) NOT NULL,
	DiasDePago NVARCHAR(50),
	Direccion NVARCHAR(100),
	Telefono NVARCHAR(30),
	NombreContacto NVARCHAR(50),
	TelefonoContacto NVARCHAR(30),
	Imagen NVARCHAR(MAX) NOT NULL,
	
	CONSTRAINT PK_CLIENTE PRIMARY KEY(Id),
	CONSTRAINT UK_Usuario_CLIENTE UNIQUE(Usuario),
	CONSTRAINT UK_Rut_CLIENTE UNIQUE(Rut),
	CONSTRAINT UK_RazonSocial_CLIENTE UNIQUE(RazonSocial)
);
GO

CREATE TABLE CATEGORIA
(
	Id	INT  NOT NULL IDENTITY(1,1),
	Nombre NVARCHAR(50) NOT NULL,
	Imagen NVARCHAR(MAX) NOT NULL,

	CONSTRAINT PK_CATEGORIA PRIMARY KEY(Id),
	CONSTRAINT UK_Nombre_CATEGORIA UNIQUE(Nombre)
);
GO

CREATE TABLE ARTICULO
(
	Id	INT  NOT NULL IDENTITY(1,1),
	Codigo NVARCHAR(20) NOT NULL,
	Nombre NVARCHAR(50) NOT NULL,
	Descripcion NVARCHAR(250) NOT NULL,
	Precio MONEY NOT NULL,
	Stock NUMERIC(6,2) NOT NULL,
	Disponible BIT NOT NULL, --A fin de que pueda dejarlo como no disponible por si no quiere mostrarlo y no se puede eliminar por estar asociado a algún pedido.
	Destacado BIT NOT NULL,

	CONSTRAINT PK_PRODUCTO PRIMARY KEY(Id),
	CONSTRAINT UK_Codigo_ARTICULO UNIQUE(Codigo)
);
GO

CREATE TABLE IMAGEN
(
	Id	INT  NOT NULL IDENTITY(1,1),
	IdArticulo INT NOT NULL,
	Imagen NVARCHAR(MAX) NOT NULL,

	CONSTRAINT PK_IMAGEN PRIMARY KEY(Id),
	CONSTRAINT FK_IdArticulo_IMAGEN FOREIGN KEY (IdArticulo) REFERENCES ARTICULO (Id)
);
GO	

CREATE TABLE ARTICULO_CATEGORIA
(
	Id	INT  NOT NULL IDENTITY(1,1),
	IdArticulo INT NOT NULL,
	IdCategoria INT NOT NULL,

	CONSTRAINT PK_ARTICULO_CATEGORIA PRIMARY KEY(Id),
	CONSTRAINT FK_IdProducto_ARTICULO_CATEGORIA FOREIGN KEY (IdArticulo) REFERENCES ARTICULO (Id),
	CONSTRAINT FK_IdCategoria_ARTICULO_CATEGORIA FOREIGN KEY (IdCategoria) REFERENCES CATEGORIA (Id)	
);
GO

CREATE TABLE ESTADO(
	Id INT NOT NULL IDENTITY(1,1),
	Nombre NVARCHAR(30) NOT NULL,
	
	CONSTRAINT PK_ESTADO PRIMARY KEY(Id),
	CONSTRAINT UK_Nombre_ESTADO UNIQUE(Nombre)
);
GO

CREATE TABLE FILTRO
(
	Id	INT  NOT NULL IDENTITY(1,1),
	Nombre NVARCHAR(50) NOT NULL,
	Color BIT NOT NULL,

	CONSTRAINT PK_FILTRO PRIMARY KEY(Id),
	CONSTRAINT UK_Nombre_FILTRO UNIQUE(Nombre)
);
GO

CREATE TABLE FILTRO_CATEGORIA
(
	Id	INT  NOT NULL IDENTITY(1,1),
	IdFiltro INT NOT NULL,
	IdCategoria INT NOT NULL,

	CONSTRAINT PK_FILTRO_CATEGORIA PRIMARY KEY(Id),
	CONSTRAINT FK_IdPFiltro_FILTRO_CATEGORIA FOREIGN KEY (IdFiltro) REFERENCES FILTRO (Id),
	CONSTRAINT FK_IdCategoria_FILTRO_CATEGORIA FOREIGN KEY (IdCategoria) REFERENCES CATEGORIA (Id)	
);
GO

CREATE TABLE FILTRO_ARTICULO
(
	Id	INT  NOT NULL IDENTITY(1,1),
	IdFiltro INT NOT NULL,
	IdArticulo INT NOT NULL,

	CONSTRAINT PK_FILTRO_ARTICULO PRIMARY KEY(Id),
	CONSTRAINT FK_IdPFiltro_FILTRO_ARTICULO FOREIGN KEY (IdFiltro) REFERENCES FILTRO (Id),
	CONSTRAINT FK_IdArticulo_FILTRO_ARTICULO FOREIGN KEY (IdArticulo) REFERENCES ARTICULO (Id)	
);
GO

CREATE TABLE PEDIDO
(
	Id	INT  NOT NULL IDENTITY(1,1),
	FechaRealizado DATETIME NOT NULL,
	FechaEntregaSolicitada DATETIME NOT NULL,
	DescuentoCliente NUMERIC (5,2) NOT NULL,
	Iva NUMERIC (5,2) NOT NULL,
	IdCliente INT NOT NULL,
	Comentario NVARCHAR(200) NOT NULL,
	IdEstado INT NOT NULL,

	CONSTRAINT PK_PEDIDO PRIMARY KEY(Id),
	CONSTRAINT FK_IdCliente_PEDIDO FOREIGN KEY (IdCliente) REFERENCES CLIENTE (Id),
	CONSTRAINT FK_IdEstadoPedido_PEDIDO FOREIGN KEY (IdEstado) REFERENCES ESTADO (Id)
);
GO

CREATE TABLE PEDIDO_ARTICULO
(
	Id	INT  NOT NULL IDENTITY(1,1),
	IdPedido INT NOT NULL,
	IdArticulo INT NOT NULL,
	Cantidad INT NOT NULL,
	PrecioUnitario MONEY NOT NULL,

	CONSTRAINT PK_PEDIDO_ARTICULO PRIMARY KEY(Id),
	CONSTRAINT FK_IdPedido_PEDIDO_ARTICULO FOREIGN KEY (IdPedido) REFERENCES PEDIDO (Id),
	CONSTRAINT FK_IdArticulo_PEDIDO_ARTICULO FOREIGN KEY (IdArticulo) REFERENCES ARTICULO (Id)
);
GO

--ANTES DE BORRAR UNA CATEGORÍA, LE ELIMINA TODOS LOS ARTICULOS QUE TIENE ASOCIADOS
CREATE TRIGGER trg_eliminarCategoria
ON CATEGORIA
INSTEAD OF DELETE
AS
BEGIN
	DECLARE @idCategoria INT, @img INT
	SELECT @idCategoria = Id FROM DELETED
	
	DELETE FROM ARTICULO_CATEGORIA WHERE IdCategoria = @idCategoria;
	DELETE FROM CATEGORIA WHERE Id = @idCategoria;
END
GO

--ANTES DE BORRAR UN ARTICULO, LE ELIMINA TODAS LAS CATEGORIAS Y FOTOS QUE TIENE ASOCIADAS
CREATE TRIGGER trg_eliminarArticulo
ON ARTICULO
INSTEAD OF DELETE
AS
BEGIN
	DECLARE @idArticulo INT
	SELECT @idArticulo = Id FROM DELETED
	
	DELETE FROM ARTICULO_CATEGORIA WHERE IdArticulo = @idArticulo;
	DELETE FROM IMAGEN WHERE IdArticulo = @idArticulo;
	DELETE FROM ARTICULO WHERE Id = @idArticulo;
END
GO


/*
	DATOS DE PRUEBA !!!
*/
INSERT INTO ADMINISTRADOR VALUES
('ADMINISTRADOR1','123'),
('ADMINISTRADOR2','123'),
('ADMINISTRADOR3','123');

INSERT INTO CLIENTE VALUES
('CLIENTE1','123','NOMBRE FANTASIA CLIENTE 1','1','RAZ. SOC. 1',0,'LUNES y VIERNES','DIRECCION 1','1','CONTACTO CLIENTE 1','1','IMAGEN CLIENTE 1'),
('CLIENTE2','123','NOMBRE FANTASIA CLIENTE 2','2','RAZ. SOC. 2',10,'MARTES y JUEVES','DIRECCION 2','2','CONTACTO CLIENTE 2','2','IMAGEN CLIENTE 2'),
('CLIENTE3','123','NOMBRE FANTASIA CLIENTE 3','3','RAZ. SOC. 3',20,'MIERCOLES','DIRECCION 3','3','CONTACTO CLIENTE 3','3','IMAGEN CLIENTE 3'),
('CLIENTE4','123','NOMBRE FANTASIA CLIENTE 4','4','RAZ. SOC. 4',30,'MIERCOLES','DIRECCION 4','4','CONTACTO CLIENTE 4','4','IMAGEN CLIENTE 4'),
('CLIENTE5','123','NOMBRE FANTASIA CLIENTE 5','5','RAZ. SOC. 5',40,'MIERCOLES','DIRECCION 5','5','CONTACTO CLIENTE 5','5','IMAGEN CLIENTE 5');

INSERT INTO CATEGORIA VALUES
('CATEGORIA 1','IMAGEN CATEGORIA 1'),
('CATEGORIA 2','IMAGEN CATEGORIA 2'),
('CATEGORIA 3','IMAGEN CATEGORIA 3'),
('CATEGORIA 4','IMAGEN CATEGORIA 4'),
('CATEGORIA 5','IMAGEN CATEGORIA 5');

INSERT INTO ARTICULO VALUES
('COD 1','ARTICULO 1','DESCRIPCION ARTICULO 1',10,0,0,0),
('COD 2','ARTICULO 2','DESCRIPCION ARTICULO 2',20,10,1,0),
('COD 3','ARTICULO 3','DESCRIPCION ARTICULO 3',30,20,1,0),
('COD 4','ARTICULO 4','DESCRIPCION ARTICULO 4',40,30,1,0),
('COD 5','ARTICULO 5','DESCRIPCION ARTICULO 5',50,40,1,0),
('COD 6','ARTICULO 6','DESCRIPCION ARTICULO 6',60,50,1,0),
('COD 7','ARTICULO 7','DESCRIPCION ARTICULO 7',70,60,1,0),
('COD 8','ARTICULO 8','DESCRIPCION ARTICULO 8',80,70,1,0),
('COD 9','ARTICULO 9','DESCRIPCION ARTICULO 9',90,80,1,0),
('COD 10','ARTICULO 10','DESCRIPCION ARTICULO 10',100,90,1,1);

INSERT INTO IMAGEN VALUES
(1,'IMAGEN 1 ARTICULO 1'),
(1,'IMAGEN 2 ARTICULO 1'),
(1,'IMAGEN 2 ARTICULO 1'),
(2,'IMAGEN 1 ARTICULO 2'),
(3,'IMAGEN 1 ARTICULO 3'),
(4,'IMAGEN 1 ARTICULO 4'),
(4,'IMAGEN 2 ARTICULO 4'),
(5,'IMAGEN 1 ARTICULO 5'),
(6,'IMAGEN 1 ARTICULO 6'),
(7,'IMAGEN 1 ARTICULO 7'),
(8,'IMAGEN 1 ARTICULO 8'),
(9,'IMAGEN 1 ARTICULO 9'),
(10,'IMAGEN 1 ARTICULO 10'),
(10,'IMAGEN 2 ARTICULO 10'),
(1,'IMAGEN 1 ARTICULO 1'),
(1,'IMAGEN 1 ARTICULO 1');

INSERT INTO ARTICULO_CATEGORIA VALUES
(1,1),
(1,2),
(2,1),
(2,2),
(3,2),
(4,3),
(5,4),
(6,5),
(6,4),
(6,3),
(7,3),
(8,4),
(9,5),
(10,5),
(10,4),
(10,3);

INSERT INTO ESTADO VALUES
('NUEVO'),
('MODIFICADO POR CLIENTE'),
('MODIFICADO POR ADMINISTRADOR'),
('CONFIRMADO'),
('CANCELADO');

INSERT INTO FILTRO VALUES
('ORO',0),
('PLATA 950',0),
('VERDE',1),
('AZUL',1),
('AMARILLA',1),
('ROJA',1);

INSERT INTO FILTRO_CATEGORIA VALUES
(1,1),
(2,1),
(1,2),
(2,2),
(1,3),
(2,3),
(1,4),
(2,5),
(3,1),
(4,1),
(5,1),
(6,1);

INSERT INTO FILTRO_ARTICULO VALUES
(1,1),
(2,1),
(1,2),
(2,3),
(2,4),
(4,5),
(5,6),
(6,7),
(1,8),
(1,9),
(2,9),
(1,10),
(2,10),
(3,10),
(4,10),
(5,10),
(6,10);

INSERT INTO PEDIDO VALUES
('20160110','20160115',0,22,1,'Descuento: 0 - Cliente: 1 - Estado: NUEVO',1),
('20160110','20160115',10,22,2,'Descuento: 10 - Cliente: 2 - Estado: MODIFICADO POR EL CLIENTE',2),
('20160110','20160115',20,22,3,'Descuento: 20 - Cliente: 3 - Estado: MODIFICADO POR EL ADMINISTRADOR',3),
('20160101','20160102',30,22,4,'Descuento: 30 - Cliente: 4 - Estado: CONFIRMADO',4),
('20160101','20160102',10,22,4,'Descuento: 10 - Cliente: 4 - Estado: CANCELADO',5),
('20160110','20160115',30,22,4,'Descuento: 30 - Cliente: 4 - Estado: Nuevo',1),
('20160110','20160115',40,22,5,'Descuento: 40 - Cliente: 5 - Estado: MODIFICADO POR EL ADMINISTRADOR',3),
('20160101','20160102',5,22,1,'Descuento: 5 - Cliente: 1 - Estado: CANCELADO',5);

INSERT INTO PEDIDO_ARTICULO VALUES
(1,1,1,10),
(2,1,2,10),
(2,2,3,20),
(2,4,4,40),
(3,10,5,100),
(3,6,6,60),
(4,5,7,50),
(5,4,8,40),
(6,5,9,50),
(6,4,10,40),
(6,3,9,30),
(6,2,8,20),
(7,1,7,10),
(7,2,6,30),
(8,10,5,100),
(8,9,4,90);