--SELECT * FROM PARAMETRO;
--SELECT * FROM ADMINISTRADOR;
--SELECT * FROM CLIENTE;
--SELECT * FROM FILTRO;
--SELECT * FROM CATEGORIA;
--SELECT * FROM FILTRO_CATEGORIA;
--SELECT * FROM ARTICULO;
--SELECT * FROM ARTICULO_CATEGORIA;
--SELECT * FROM FILTRO_ARTICULO;
--SELECT * FROM ESTADO ORDER BY Id;
--SELECT * FROM PEDIDO;
--SELECT * FROM PEDIDO_ARTICULO;
--SELECT * FROM IMAGEN;

--USE master;
--GO

--DROP DATABASE ProyectoWeb_Catalogo_Pedidos;
--GO

CREATE DATABASE ProyectoWeb_Catalogo_Pedidos;
GO

USE ProyectoWeb_Catalogo_Pedidos;
GO

CREATE TABLE PARAMETRO
(
	Id INT NOT NULL IDENTITY(1,1),
	IVA NUMERIC(5,2) NOT NULL,
	
	CONSTRAINT PK_PARAMETRO PRIMARY KEY(Id)
);
GO

CREATE TABLE ADMINISTRADOR
(
	Id INT NOT NULL IDENTITY(1,1),
	Usuario NVARCHAR(20) NOT NULL,
	Contrasenia NVARCHAR(MAX) NOT NULL,
	EnConstruccion INT,
	
	CONSTRAINT PK_ADMINISTRADOR PRIMARY KEY(Id),
	CONSTRAINT UK_Usuario_ADMINISTRADOR UNIQUE(Usuario)
);
GO

CREATE TABLE CLIENTE
(
	Id INT NOT NULL IDENTITY(1,1),
	Usuario NVARCHAR(20) NOT NULL,
	Contrasenia NVARCHAR(MAX) NOT NULL,
	EnConstruccion INT,
	NombreFantasia NVARCHAR(100) NOT NULL,
	Rut NVARCHAR(50),
	RazonSocial NVARCHAR(100),
	Descuento NUMERIC(5,2) NOT NULL,
	DiasDePago NVARCHAR(50),
	Direccion NVARCHAR(100),
	Telefono NVARCHAR(30),
	NombreContacto NVARCHAR(50),
	TelefonoContacto NVARCHAR(30),
	EmailContacto NVARCHAR(50),
	Imagen NVARCHAR(MAX) NOT NULL,
	Habilitado BIT NOT NULL
	
	CONSTRAINT PK_CLIENTE PRIMARY KEY(Id),
	CONSTRAINT UK_Usuario_CLIENTE UNIQUE(Usuario),
	--CONSTRAINT UK_Rut_CLIENTE UNIQUE(Rut),
	--CONSTRAINT UK_RazonSocial_CLIENTE UNIQUE(RazonSocial),
	--CONSTRAINT UK_NombreFantasia_CLIENTE UNIQUE(NombreFantasia)
);
GO

CREATE TABLE CATEGORIA
(
	Id	INT  NOT NULL IDENTITY(1,1),
	Nombre NVARCHAR(50) NOT NULL,
	Imagen NVARCHAR(MAX) NOT NULL,
	Destacado BIT NOT NULL,

	CONSTRAINT PK_CATEGORIA PRIMARY KEY(Id),
	CONSTRAINT UK_Nombre_CATEGORIA UNIQUE(Nombre)
);
GO

CREATE TABLE ARTICULO
(
	Id	INT  NOT NULL IDENTITY(1,1),
	Codigo NVARCHAR(20) NOT NULL,
	Nombre NVARCHAR(50) NOT NULL,
	Descripcion NVARCHAR(250) NOT NULL,
	Precio MONEY NOT NULL,
	Stock NUMERIC(6,2) NOT NULL,
	Disponible BIT NOT NULL, --A fin de que pueda dejarlo como no disponible por si no quiere mostrarlo y no se puede eliminar por estar asociado a algún pedido.
	Destacado BIT NOT NULL,

	CONSTRAINT PK_PRODUCTO PRIMARY KEY(Id),
	CONSTRAINT UK_Codigo_ARTICULO UNIQUE(Codigo)
);
GO

CREATE TABLE IMAGEN
(
	Id	INT  NOT NULL IDENTITY(1,1),
	IdArticulo INT NOT NULL,
	Imagen NVARCHAR(MAX) NOT NULL,

	CONSTRAINT PK_IMAGEN PRIMARY KEY(Id),
	CONSTRAINT FK_IdArticulo_IMAGEN FOREIGN KEY (IdArticulo) REFERENCES ARTICULO (Id)
);
GO	

CREATE TABLE ARTICULO_CATEGORIA
(
	Id	INT  NOT NULL IDENTITY(1,1),
	IdArticulo INT NOT NULL,
	IdCategoria INT NOT NULL,

	CONSTRAINT PK_ARTICULO_CATEGORIA PRIMARY KEY(Id),
	CONSTRAINT FK_IdProducto_ARTICULO_CATEGORIA FOREIGN KEY (IdArticulo) REFERENCES ARTICULO (Id),
	CONSTRAINT FK_IdCategoria_ARTICULO_CATEGORIA FOREIGN KEY (IdCategoria) REFERENCES CATEGORIA (Id)	
);
GO

CREATE TABLE ESTADO(
	Id INT NOT NULL IDENTITY(1,1),
	Nombre NVARCHAR(30) NOT NULL,
	
	CONSTRAINT PK_ESTADO PRIMARY KEY(Id),
	CONSTRAINT UK_Nombre_ESTADO UNIQUE(Nombre)
);
GO

CREATE TABLE FILTRO
(
	Id	INT  NOT NULL IDENTITY(1,1),
	Nombre NVARCHAR(50) NOT NULL,
	Color BIT NOT NULL,

	CONSTRAINT PK_FILTRO PRIMARY KEY(Id),
	CONSTRAINT UK_Nombre_FILTRO UNIQUE(Nombre)
);
GO

CREATE TABLE FILTRO_CATEGORIA
(
	Id	INT  NOT NULL IDENTITY(1,1),
	IdFiltro INT NOT NULL,
	IdCategoria INT NOT NULL,

	CONSTRAINT PK_FILTRO_CATEGORIA PRIMARY KEY(Id),
	CONSTRAINT FK_IdPFiltro_FILTRO_CATEGORIA FOREIGN KEY (IdFiltro) REFERENCES FILTRO (Id),
	CONSTRAINT FK_IdCategoria_FILTRO_CATEGORIA FOREIGN KEY (IdCategoria) REFERENCES CATEGORIA (Id)	
);
GO

CREATE TABLE FILTRO_ARTICULO
(
	Id	INT  NOT NULL IDENTITY(1,1),
	IdFiltro INT NOT NULL,
	IdArticulo INT NOT NULL,

	CONSTRAINT PK_FILTRO_ARTICULO PRIMARY KEY(Id),
	CONSTRAINT FK_IdPFiltro_FILTRO_ARTICULO FOREIGN KEY (IdFiltro) REFERENCES FILTRO (Id),
	CONSTRAINT FK_IdArticulo_FILTRO_ARTICULO FOREIGN KEY (IdArticulo) REFERENCES ARTICULO (Id)	
);
GO

CREATE TABLE PEDIDO
(
	Id	INT  NOT NULL IDENTITY(1,1),
	FechaRealizado DATETIME NOT NULL,
	FechaEntregaSolicitada DATETIME NOT NULL,
	DescuentoCliente NUMERIC (5,2) NOT NULL,
	Iva NUMERIC (5,2) NOT NULL,
	IdCliente INT NOT NULL,
	Comentario NVARCHAR(200),
	IdEstado INT NOT NULL,

	CONSTRAINT PK_PEDIDO PRIMARY KEY(Id),
	CONSTRAINT FK_IdCliente_PEDIDO FOREIGN KEY (IdCliente) REFERENCES CLIENTE (Id),
	CONSTRAINT FK_IdEstadoPedido_PEDIDO FOREIGN KEY (IdEstado) REFERENCES ESTADO (Id)
);
GO

ALTER TABLE CLIENTE
	ADD CONSTRAINT FK_EnConstruccion_CLIENTE FOREIGN KEY (EnConstruccion) REFERENCES PEDIDO (Id);
GO
ALTER TABLE ADMINISTRADOR
	ADD CONSTRAINT FK_EnConstruccion_ADMINISTRADOR FOREIGN KEY (EnConstruccion) REFERENCES PEDIDO (Id);
GO

CREATE TABLE PEDIDO_ARTICULO
(
	Id	INT  NOT NULL IDENTITY(1,1),
	IdPedido INT NOT NULL,
	IdArticulo INT NOT NULL,
	Cantidad INT NOT NULL,
	PrecioUnitario MONEY NOT NULL,

	CONSTRAINT PK_PEDIDO_ARTICULO PRIMARY KEY(Id),
	CONSTRAINT FK_IdPedido_PEDIDO_ARTICULO FOREIGN KEY (IdPedido) REFERENCES PEDIDO (Id),
	CONSTRAINT FK_IdArticulo_PEDIDO_ARTICULO FOREIGN KEY (IdArticulo) REFERENCES ARTICULO (Id)
);
GO
--despues de cambiar el precio de un articulo
CREATE TRIGGER trg_actualizarPrecioEstadoPedidoEnConstruccion
ON ARTICULO
AFTER UPDATE
AS
BEGIN
	DECLARE @idArticulo INT, @precio INT, @estado BIT
	SELECT @idArticulo = Id, @precio = Precio, @estado = Disponible  FROM inserted
	
	UPDATE PEDIDO_ARTICULO SET PrecioUnitario = @precio WHERE IdArticulo=@idArticulo 
	and IdPedido in (SELECT IdPedido FROM PEDIDO P WHERE IdEstado = 5)  --OJO SI CAMBIAS LOS ESTADOS CAMBIA EL NUEMRO
	
	IF @estado = 0
		BEGIN
			DELETE PEDIDO_ARTICULO WHERE IdArticulo=@idArticulo
			and IdPedido in (SELECT IdPedido FROM PEDIDO P WHERE IdEstado = 5)  --OJO SI CAMBIAS LOS ESTADOS CAMBIA EL NUEMRO
		END
END
GO

--ANTES DE BORRAR UNA CATEGORÍA, LE ELIMINA TODOS LOS ARTICULOS QUE TIENE ASOCIADOS
CREATE TRIGGER trg_eliminarCategoria
ON CATEGORIA
INSTEAD OF DELETE
AS
BEGIN
	DECLARE @idCategoria INT, @img INT
	SELECT @idCategoria = Id FROM DELETED
	
	DELETE FROM ARTICULO_CATEGORIA WHERE IdCategoria = @idCategoria;
	DELETE FROM CATEGORIA WHERE Id = @idCategoria;
END
GO

--ANTES DE BORRAR UN ARTICULO, LE ELIMINA TODAS LAS CATEGORIAS Y FOTOS QUE TIENE ASOCIADAS
CREATE TRIGGER trg_eliminarArticulo
ON ARTICULO
INSTEAD OF DELETE
AS
BEGIN
	DECLARE @idArticulo INT
	SELECT @idArticulo = Id FROM DELETED
	
	DELETE FROM ARTICULO_CATEGORIA WHERE IdArticulo = @idArticulo;
	DELETE FROM IMAGEN WHERE IdArticulo = @idArticulo;
	DELETE FROM ARTICULO WHERE Id = @idArticulo;
END
GO


/*
	DATOS DE PRUEBA !!!
*/
INSERT INTO PARAMETRO VALUES
(22);

INSERT INTO ADMINISTRADOR VALUES
--Los password de Prueba son: 123
('ADMINISTRADOR1','202cb962ac59075b964b07152d234b70', NULL),
('ADMINISTRADOR2','202cb962ac59075b964b07152d234b70', NULL),
('ADMINISTRADOR3','202cb962ac59075b964b07152d234b70', NULL);

INSERT INTO CLIENTE VALUES
--Los password de Prueba son: 123
('CLIENTE1','202cb962ac59075b964b07152d234b70', NULL,'NOMBRE FANTASIA CLIENTE 1','1','RAZ. SOC. 1',0,'LUNES y VIERNES','DIRECCION 1','1','CONTACTO CLIENTE 1','1','EMAIL1@EMAIL.COM','CLIENTE1.jpg',1),
('CLIENTE2','202cb962ac59075b964b07152d234b70', NULL,'NOMBRE FANTASIA CLIENTE 2','2','RAZ. SOC. 2',10,'MARTES y JUEVES','DIRECCION 2','2','CONTACTO CLIENTE 2','2','EMAIL2@EMAIL.COM','CLIENTE2.jpg',1),
('CLIENTE3','202cb962ac59075b964b07152d234b70', NULL,'NOMBRE FANTASIA CLIENTE 3','3','RAZ. SOC. 3',20,'MIERCOLES','DIRECCION 3','3','CONTACTO CLIENTE 3','3','EMAIL3@EMAIL.COM','CLIENTE3.jpg',1),
('CLIENTE4','202cb962ac59075b964b07152d234b70', NULL,'NOMBRE FANTASIA CLIENTE 4','4','RAZ. SOC. 4',30,'MIERCOLES','DIRECCION 4','4','CONTACTO CLIENTE 4','4','EMAIL4@EMAIL.COM','CLIENTE4.jpg',1),
('CLIENTE5','202cb962ac59075b964b07152d234b70', NULL,'NOMBRE FANTASIA CLIENTE 5','5','RAZ. SOC. 5',40,'MIERCOLES','DIRECCION 5','5','CONTACTO CLIENTE 5','5','EMAIL5@EMAIL.COM','CLIENTE5.jpg',1);

INSERT INTO CATEGORIA VALUES
('Anillos','CAT1.jpg',1),
('Caravanas','CAT2.jpg',1),
('Collares','CAT3.jpg',1),
('Pulseras','CAT4.jpg',1),
('Otros','CAT5.jpg',1);

INSERT INTO ARTICULO VALUES
('COD 1','Artículo 1','Descripción Artículo 1',10,0,1,1),
('COD 2','Artículo 2','Descripción Artículo 2',20,10,1,1),
('COD 3','Artículo 3','Descripción Artículo 3',30,20,1,1),
('COD 4','Artículo 4','Descripción Artículo 4',40,30,1,1),
('COD 5','Artículo 5','Descripción Artículo 5',50,40,1,1),
('COD 6','Artículo 6','Descripción Artículo 6',60,50,1,1),
('COD 7','Artículo 7','Descripción Artículo 7',70,60,1,0),
('COD 8','Artículo 8','Descripción Artículo 8',80,70,1,0),
('COD 9','Artículo 9','Descripción Artículo 9',90,80,1,0),
('COD 10','Artículo 10','Descripción Artículo 10',100,90,1,1),
('COD 11','Artículo 11','Descripción Artículo 11',10,80,1,1);

INSERT INTO IMAGEN VALUES
(1,'ART1_IMG1.jpg'),
(1,'ART1_IMG2.jpg'),
(1,'ART1_IMG3.jpg'),
(2,'ART2_IMG1.jpg'),
(3,'ART3_IMG1.jpg'),
(3,'ART3_IMG2.jpg'),
(4,'ART4_IMG1.jpg'),
(4,'ART4_IMG2.jpg'),
(5,'ART5_IMG1.jpg'),
(6,'ART6_IMG1.jpg'),
(7,'ART7_IMG1.jpg'),
(8,'ART8_IMG1.jpg'),
(9,'ART9_IMG1.jpg'),
(10,'ART10_IMG1.jpg'),
(10,'ART10_IMG2.jpg'),
(1,'ART1_IMG4.jpg'),
(1,'ART1_IMG5.jpg'),
(11,'ART11_IMG1.jpg'),
(11,'ART11_IMG2.jpg'),
(11,'ART11_IMG3.jpg');

INSERT INTO ARTICULO_CATEGORIA VALUES
(1,1),
(2,1),
(3,2),
(4,3),
(5,4),
(6,3),
(7,3),
(8,4),
(9,5),
(10,5),
(10,4),
(11,1);

INSERT INTO ESTADO VALUES
('CONFIRMADO POR CLIENTE'),
('MODIFICADO POR ADMINISTRADOR'),
('REALIZADO'),
('CANCELADO'),
('EN CONSTRUCCION');

INSERT INTO FILTRO VALUES
('Plata 925',0),
('Verde',1),
('Azul',1),
('Amarillo',1),
('Rojo',1);

INSERT INTO FILTRO_CATEGORIA VALUES
(1,1),
(2,1),
(1,2),
(2,2),
(1,3),
(2,3),
(1,4),
(2,5),
(3,1),
(4,1),
(5,1);

INSERT INTO FILTRO_ARTICULO VALUES
(1,1),
(2,1),
(1,2),
(2,3),
(2,4),
(4,5),
(5,6),
(1,8),
(1,9),
(2,9),
(1,10),
(2,10),
(3,10),
(4,10),
(5,10),
(1,11);

INSERT INTO PEDIDO VALUES
('20160215','20160315',0,22,1,'Descuento: 0 - Cliente: 1 - Estado: CONFIRMADO POR CLIENTE',1),
('20160110','20160115',10,22,2,'Descuento: 10 - Cliente: 2 - Estado: CONFIRMADO POR CLIENTE',1),
('20160110','20160115',20,22,3,'Descuento: 20 - Cliente: 3 - Estado: MODIFICADO POR EL ADMINISTRADOR',2),
('20160101','20160102',30,22,4,'Descuento: 30 - Cliente: 4 - Estado: CONFIRMADO',3),
('20160101','20160102',10,22,4,'Descuento: 10 - Cliente: 4 - Estado: CANCELADO',4),
('20160426','20160520',30,22,4,'Descuento: 30 - Cliente: 4 - Estado: CONFIRMADO POR CLIENTE',1),
('20160110','20160115',40,22,5,'Descuento: 40 - Cliente: 5 - Estado: EN CONSTRUCCION',1),
('20160101','20160102',5,22,1,'Descuento: 5 - Cliente: 1 - Estado: CANCELADO',4);

INSERT INTO PEDIDO_ARTICULO VALUES
(1,1,1,10),
(2,1,2,10),
(2,2,3,20),
(2,4,4,40),
(3,10,5,100),
(3,6,6,60),
(4,5,7,50),
(5,4,8,40),
(6,5,9,50),
(6,4,10,40),
(6,3,9,30),
(6,2,8,20),
(7,1,7,10),
(7,2,6,30),
(8,10,5,100),
(8,9,4,90);